// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_local_weights
NumericMatrix calc_local_weights(NumericVector w, NumericMatrix G);
RcppExport SEXP _multigrain_calc_local_weights(SEXP wSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_local_weights(w, G));
    return rcpp_result_gen;
END_RCPP
}
// esch_population_rcpp
Rcpp::NumericMatrix esch_population_rcpp(int popSize, int nBits, Rcpp::NumericVector lower, Rcpp::NumericVector upper);
RcppExport SEXP _multigrain_esch_population_rcpp(SEXP popSizeSEXP, SEXP nBitsSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type popSize(popSizeSEXP);
    Rcpp::traits::input_parameter< int >::type nBits(nBitsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(esch_population_rcpp(popSize, nBits, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// esch_mutation_rcpp
Rcpp::NumericVector esch_mutation_rcpp(Rcpp::NumericVector parent, Rcpp::NumericVector lower, Rcpp::NumericVector upper);
RcppExport SEXP _multigrain_esch_mutation_rcpp(SEXP parentSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(esch_mutation_rcpp(parent, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// graph_shortcut
LogicalMatrix graph_shortcut(const NumericMatrix& pvals, const double alpha, const NumericVector& w, const NumericMatrix& G);
RcppExport SEXP _multigrain_graph_shortcut(SEXP pvalsSEXP, SEXP alphaSEXP, SEXP wSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_shortcut(pvals, alpha, w, G));
    return rcpp_result_gen;
END_RCPP
}
// graph_shortcut_parallel
LogicalMatrix graph_shortcut_parallel(const NumericMatrix& pvals, const double alpha, const NumericVector& w, const NumericMatrix& G, int num_threads, int grain_size);
RcppExport SEXP _multigrain_graph_shortcut_parallel(SEXP pvalsSEXP, SEXP alphaSEXP, SEXP wSEXP, SEXP GSEXP, SEXP num_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_shortcut_parallel(pvals, alpha, w, G, num_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// graph_violation_score_cpp
double graph_violation_score_cpp(NumericVector w, NumericMatrix G);
RcppExport SEXP _multigrain_graph_violation_score_cpp(SEXP wSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_violation_score_cpp(w, G));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multigrain_calc_local_weights", (DL_FUNC) &_multigrain_calc_local_weights, 2},
    {"_multigrain_esch_population_rcpp", (DL_FUNC) &_multigrain_esch_population_rcpp, 4},
    {"_multigrain_esch_mutation_rcpp", (DL_FUNC) &_multigrain_esch_mutation_rcpp, 3},
    {"_multigrain_graph_shortcut", (DL_FUNC) &_multigrain_graph_shortcut, 4},
    {"_multigrain_graph_shortcut_parallel", (DL_FUNC) &_multigrain_graph_shortcut_parallel, 6},
    {"_multigrain_graph_violation_score_cpp", (DL_FUNC) &_multigrain_graph_violation_score_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_multigrain(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
