# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate the local weighting strategy for all intersection hypotheses
#'
#' @description
#' Computes the closure-based weighting strategy for a graphical multiple
#' testing procedure: for each of the \eqn{2^m - 1} intersection
#' hypotheses. Returns a combined matrix of intersection
#' membership indicators and hypothesis weights.
#'
#' @param w `NumericVector` (length m) of initial local hypothesis weights.
#' @param G `NumericMatrix` (m x m) initial transition matrix.
#' @returns `NumericMatrix` (\eqn{2^m - 1} x \eqn{2m}). The first m columns
#'   are 0/1 intersection-membership indicators; the second m columns are
#'   the corresponding local hypothesis weights (0 where the hypothesis
#'   is not in that intersection).
#'
#' @note
#' This function implements Algorithm 1 of Bretz et al. (2011). The output
#' follows the convention established in
#' `gMCP::generateWeights()` and
#' `graphicalMCP::graph_generate_weights()`.
#'
#' @references
#' Bretz, F., Maurer, W., Brannath, W., and Posch, M. (2009). A graphical
#' approach to sequentially rejective multiple test procedures.
#' Statistics in Medicine, 28(4), 586--604.
#' <https://doi.org/10.1002/sim.3495>
#'
#' Bretz, F., Posch, M., Glimm, E., Klinglmueller, F., Maurer, W., and
#' Rohmeyer, K. (2011). Graphical approaches for multiple comparison
#' procedures using weighted Bonferroni, Simes, or parametric tests.
#' Biometrical Journal, 53(6), 894--913.
#' <https://doi.org/10.1002/bimj.201000239>
#'
#' @noRd
calc_local_weights <- function(w, G) {
    .Call(`_multigrain_calc_local_weights`, w, G)
}

esch_population_rcpp <- function(popSize, nBits, lower, upper) {
    .Call(`_multigrain_esch_population_rcpp`, popSize, nBits, lower, upper)
}

esch_mutation_rcpp <- function(parent, lower, upper) {
    .Call(`_multigrain_esch_mutation_rcpp`, parent, lower, upper)
}

#' Graphical shortcut algorithm (Bretz et al. 2009) -- fast serial backend
#'
#' Applies the sequentially rejective graphical test procedure to a matrix of
#' simulated p-values and returns only the rejection matrix (no adjusted
#' alphas or graph history). Matches the behaviour of gMCPLite::graphTest()
#' in the non-parametric, non-entangled, non-upscale case.
#'
#' @param pvals NumericMatrix (N x m) of simulated p-values.
#' @param alpha Scalar significance level.
#' @param w NumericVector (length m) of hypothesis weights.
#' @param G NumericMatrix (m x m) transition matrix. Diagonal must be 0,
#'   row sums must be <= 1.
#' @return LogicalMatrix (N x m) of rejection indicators.
#'
#' @seealso \code{\link{graph_shortcut_parallel}} for the multithreaded variant.
#' @name graph_shortcut
#' @noRd
graph_shortcut <- function(pvals, alpha, w, G) {
    .Call(`_multigrain_graph_shortcut`, pvals, alpha, w, G)
}

#' Graphical shortcut algorithm (Bretz et al. 2009) -- parallel backend
#'
#' Multithreaded implementation of the shortcut algorithm via RcppParallel,
#' parallelised across trials. Matches the behaviour of gMCPLite::graphTest()
#' in the non-parametric, non-entangled, non-upscale case.
#'
#' @param pvals NumericMatrix (N x m) of simulated p-values.
#' @param alpha Scalar significance level.
#' @param w NumericVector (length m) of hypothesis weights.
#' @param G NumericMatrix (m x m) transition matrix. Diagonal must be 0,
#'   row sums must be <= 1.
#' @param num_threads Number of parallel threads (>= 1). Default 1.
#' @param grain_size Chunk size for parallelFor. Default -1 (auto-tuned).
#'   When negative, grain size is chosen so each chunk does approximately
#'   TARGET_OPS worth of inner-loop operations. Per-trial work is O(m^3)
#'   worst case (up to m rejections, each triggering an m*m graph update);
#'   TARGET_OPS = 100000 gives ~195 trials/chunk at m=8 and ~800 trials/chunk
#'   at m=5, leaving thousands of chunks at N=1e6 for good load balancing.
#'
#' @return LogicalMatrix (N x m) of rejection indicators.
#'
#' @seealso \code{\link{graph_shortcut}} for the single-threaded variant.
#' @name graph_shortcut_parallel
#' @noRd
graph_shortcut_parallel <- function(pvals, alpha, w, G, num_threads = 1L, grain_size = -1L) {
    .Call(`_multigrain_graph_shortcut_parallel`, pvals, alpha, w, G, num_threads, grain_size)
}

#' Graph violation score
#'
#' Computes scalar violation score used to penalise invalid graphs during
#' optimisation
#'
#' @param w numeric vector of weights (length m).
#' @param G numeric matrix (m x m) of edge weights.
#' @return scalar violation score (double).
#'
#' @noRd
graph_violation_score_cpp <- function(w, G) {
    .Call(`_multigrain_graph_violation_score_cpp`, w, G)
}

